### ISSUE TITLE
The highlight circles do not use the selected color on startup

### ISSUE THREAD

**Issue by andrezgz** [JeremiahKoeiman/obsidian-note-highlighter#2]
The color setting is set to a yellow. When I first open the vault, the highlight circle next to each note is black.
If I change the color setting, the circle gets that color.

These are the css styles from the developers tools after starting Obsidian:

```css
.obsidian-todo-note-highlighter {
    position: absolute;
    width: var(--note-highlighter-size);
    height: var(--note-highlighter-size);
    background-color: var(--note-highlighter-color);
    border-radius: 50%;
    right: 5px;
    top: 50%;
    transform: translateY(-50%);
}

:root {
    --note-highlighter-size: 15px;
    --note-highlighter-color: rgb(0, 0, 0);
}
```
